// Port generated by mpv-libretro of the Dot shader by Themaister, released into the public domain.
// https://github.com/libretro/glsl-shaders/blob/2b2c5ee3fd8e1a3884e20ed424fd9bfbc51cbb3d/handheld/shaders/dot.glsl
// https://github.com/hhirtz/mpv-retro-shaders/blob/master/dot.glsl

[vertex]
attribute vec2 a_position;
attribute vec2 a_texcoords;

varying vec2 v_texcoords;

void main()
{
    v_texcoords = a_texcoords;
    gl_Position = vec4(a_position, 0.0, 1.0);
}

[fragment]
uniform sampler2D u_texture;
uniform vec2 u_screenSize;

varying vec2 v_texcoords;

vec4 linearize(vec4 color)
{
    const float _const_0_1 = 0.05958483740687370300;
    const float _const_1_1 = 0.87031054496765136718;
    color.rgb = max(color.rgb, 0.0);
    color.rgb = _const_1_1 * pow(color.rgb + vec3(_const_0_1), vec3(2.4));
    return color;
}

vec4 delinearize(vec4 color)
{
    const float _const_0_2 = 0.05958483740687370300;
    const float _const_1_2 = 1.14901518821716308593;
    color.rgb = max(color.rgb, 0.0);
    color.rgb = pow(_const_1_2 * color.rgb, vec3(1.0/2.4)) - vec3(_const_0_2);
    return color;
}

float dist_func(vec2 coord, vec2 source)
{
    vec2 delta = coord - source;
    return sqrt(dot(delta, delta));
}

float color_bloom(vec3 color)
{
    const vec3 gray_coeff = vec3(0.3, 0.59, 0.11);
    float bright = dot(color, gray_coeff);
    return mix(1.0 + 0.05, 1.0 - 0.05, bright);
}

vec3 lookup(vec2 pixel_no, float offset_x, float offset_y, vec3 color)
{
    vec2 offset = vec2(offset_x, offset_y);
    float delta = dist_func(fract(pixel_no), offset + vec2(0.5, 0.5));
    return color * exp(-2.4 * delta * color_bloom(color));
}

void main()
{
    vec2 pixel_no = v_texcoords * u_screenSize;
    vec3 base = linearize(texture2D(u_texture, v_texcoords)).rgb;

    vec3 mid_color = lookup(pixel_no, 0.0, 0.0, base);
    vec3 color = vec3(0.0, 0.0, 0.0);
    color += lookup(pixel_no, -1.0, -1.0, base);
    color += lookup(pixel_no, 0.0, -1.0, base);
    color += lookup(pixel_no, 1.0, -1.0, base);
    color += lookup(pixel_no, -1.0, 0.0, base);
    color += mid_color;
    color += lookup(pixel_no, 1.0, 0.0, base);
    color += lookup(pixel_no, -1.0, 1.0, base);
    color += lookup(pixel_no, 0.0, 1.0, base);
    color += lookup(pixel_no, 1.0, 1.0, base);
    vec3 out_color = mix(1.2 * mid_color, color, 0.65);
    gl_FragColor = delinearize(vec4(out_color, 1.0));
}
