// Port of Hyllian's CRT Shader, generated by mpv-retro
// https://github.com/libretro/glsl-shaders/blob/master/crt/shaders/hyllian/crt-hyllian.glsl
// https://github.com/hhirtz/mpv-retro-shaders/blob/master/crt-hyllian.glsl
//
// Copyright (C) 2011-2020 Hyllian - sergiogdb@gmail.com
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

[vertex]
attribute vec2 a_position;
attribute vec2 a_texcoords;

varying vec2 v_texcoords;

void main()
{
    v_texcoords = a_texcoords;
    gl_Position = vec4(a_position, 0.0, 1.0);
}

[fragment]
uniform sampler2D u_texture;
uniform vec2 u_screenSize;

varying vec2 v_texcoords;

#define BEAM_PROFILE 0.0
#define HFILTER_PROFILE 0.0
#define BEAM_MIN_WIDTH 1.0
#define BEAM_MAX_WIDTH 1.0
#define SCANLINES_STRENGTH 0.58
#define COLOR_BOOST 1.3
#define SHARPNESS_HACK 1.0
#define PHOSPHOR_LAYOUT 4.0
#define MASK_INTENSITY 0.7
#define CRT_ANTI_RINGING 1.0
#define InputGamma 2.4
#define OutputGamma 2.2
#define VSCANLINES 0.0

vec4 linearize(vec4 color)
{
    const float _const_0_1 = 0.05958483740687370300;
    const float _const_1_1 = 0.87031054496765136718;
    color.rgb = max(color.rgb, 0.0);
    color.rgb = _const_1_1 * pow(color.rgb + vec3(_const_0_1), vec3(2.4));
    return color;
}

vec4 delinearize(vec4 color)
{
    const float _const_0_2 = 0.05958483740687370300;
    const float _const_1_2 = 1.14901518821716308593;
    color.rgb = max(color.rgb, 0.0);
    color.rgb = pow(_const_1_2 * color.rgb, vec3(1.0/2.4)) - vec3(_const_0_2);
    return color;
}

void main()
{
    vec4 profile = vec4(SCANLINES_STRENGTH, BEAM_MIN_WIDTH, BEAM_MAX_WIDTH, COLOR_BOOST);
    if (BEAM_PROFILE == 1.0) profile = vec4(0.62, 1.0, 1.0, 1.4);
    if (BEAM_PROFILE == 2.0) profile = vec4(0.72, 1.0, 1.0, 1.2);

    vec2 TextureSize = mix(vec2(u_screenSize.x * SHARPNESS_HACK, u_screenSize.y), vec2(u_screenSize.x, u_screenSize.y * SHARPNESS_HACK), VSCANLINES);
    vec2 dx = mix(vec2(1.0 / TextureSize.x, 0.0), vec2(0.0, 1.0 / TextureSize.y), VSCANLINES);
    vec2 dy = mix(vec2(0.0, 1.0 / TextureSize.y), vec2(1.0 / TextureSize.x, 0.0), VSCANLINES);
    vec2 pix_coord = v_texcoords.xy * TextureSize + vec2(-0.5, 0.5);
    vec2 tc = mix((floor(pix_coord) + vec2(0.5, 0.5)) / TextureSize, (floor(pix_coord) + vec2(1.5, -0.5)) / TextureSize, VSCANLINES);
    vec2 fp = mix(fract(pix_coord), fract(pix_coord.yx), VSCANLINES);
    vec3 c00 = pow(linearize(texture2D(u_texture, tc - dx - dy)).xyz, vec3(InputGamma, InputGamma, InputGamma));
    vec3 c01 = pow(linearize(texture2D(u_texture, tc - dy)).xyz, vec3(InputGamma, InputGamma, InputGamma));
    vec3 c02 = pow(linearize(texture2D(u_texture, tc + dx - dy)).xyz, vec3(InputGamma, InputGamma, InputGamma));
    vec3 c03 = pow(linearize(texture2D(u_texture, tc + 2.0 * dx - dy)).xyz, vec3(InputGamma, InputGamma, InputGamma));
    vec3 c10 = pow(linearize(texture2D(u_texture, tc - dx)).xyz, vec3(InputGamma, InputGamma, InputGamma));
    vec3 c11 = pow(linearize(texture2D(u_texture, tc)).xyz, vec3(InputGamma, InputGamma, InputGamma));
    vec3 c12 = pow(linearize(texture2D(u_texture, tc + dx)).xyz, vec3(InputGamma, InputGamma, InputGamma));
    vec3 c13 = pow(linearize(texture2D(u_texture, tc + 2.0 * dx)).xyz, vec3(InputGamma, InputGamma, InputGamma));

    float bf = 0.0;
    float cf = 0.0;
    if (HFILTER_PROFILE == 1.0) {
        bf = 0.0;
        cf = 0.5;
    }
    mat4 invX = mat4(
        (-bf - 6.0 * cf) / 6.0, (3.0 * bf + 12.0 * cf) / 6.0, (-3.0 * bf - 6.0 * cf) / 6.0, bf / 6.0,
        (12.0 - 9.0 * bf - 6.0 * cf) / 6.0, (-18.0 + 12.0 * bf + 6.0 * cf) / 6.0, 0.0, (6.0 - 2.0 * bf) / 6.0,
        -(12.0 - 9.0 * bf - 6.0 * cf) / 6.0, (18.0 - 15.0 * bf - 12.0 * cf) / 6.0, (3.0 * bf + 6.0 * cf) / 6.0, bf / 6.0,
        (bf + 6.0 * cf) / 6.0, -cf, 0.0, 0.0
    );
    vec4 invX_Px = vec4(fp.x * fp.x * fp.x, fp.x * fp.x, fp.x, 1.0) * invX;

    vec3 color0 = c00 * invX_Px.x + c01 * invX_Px.y + c02 * invX_Px.z + c03 * invX_Px.w;
    vec3 color1 = c10 * invX_Px.x + c11 * invX_Px.y + c12 * invX_Px.z + c13 * invX_Px.w;

    vec3 min_sample0 = min(c01, c02);
    vec3 max_sample0 = max(c01, c02);
    vec3 min_sample1 = min(c11, c12);
    vec3 max_sample1 = max(c11, c12);
    vec3 aux = color0;
    color0 = clamp(color0, min_sample0, max_sample0);
    color0 = mix(aux, color0, CRT_ANTI_RINGING * step(0.0, (c00 - c01) * (c02 - c03)));
    aux = color1;
    color1 = clamp(color1, min_sample1, max_sample1);
    color1 = mix(aux, color1, CRT_ANTI_RINGING * step(0.0, (c10 - c11) * (c12 - c13)));
    float pos0 = fp.y;
    float pos1 = 1.0 - fp.y;
    vec3 lum0 = mix(vec3(profile.y), vec3(profile.z), color0);
    vec3 lum1 = mix(vec3(profile.y), vec3(profile.z), color1);
    vec3 d0 = 4.0 * profile.x * pos0 / (lum0 * lum0 + 0.0000001);
    vec3 d1 = 4.0 * profile.x * pos1 / (lum1 * lum1 + 0.0000001);
    d0 = exp(-d0 * d0);
    d1 = exp(-d1 * d1);
    vec3 color = profile.w * (color0 * d0 + color1 * d1);
    vec2 mask_coords = v_texcoords.xy * u_screenSize;
    mask_coords = mix(mask_coords.xy, mask_coords.yx, VSCANLINES);

    float on = 1.0;
    float off = 1.0 - MASK_INTENSITY;
    vec3 red = vec3(on, off, off);
    vec3 green = vec3(off, on, off);
    vec3 blue = vec3(off, off, on);
    vec3 magenta = vec3(on, off, on);
    vec3 yellow = vec3(on, on, off);
    vec3 cyan = vec3(off, on, on);
    vec3 black = vec3(off, off, off);
    vec3 white = vec3(on, on, on);

    vec3 mask_weight = vec3(1.0);
    int phosphor = int(PHOSPHOR_LAYOUT);
    if (phosphor == 1) {
        mask_weight = mix(magenta, green, floor(mod(mask_coords.x, 2.0)));
    } else if (phosphor == 2) {
        vec3 ap = mix(magenta, green, floor(mod(mask_coords.x, 2.0)));
        vec3 inv_ap = mix(green, magenta, floor(mod(mask_coords.x, 2.0)));
        mask_weight = mix(ap, inv_ap, floor(mod(mask_coords.y, 2.0)));
    } else if (phosphor == 3) {
        vec3 slotmask[12] = vec3[12](magenta, green, black, black, magenta, green, magenta, green, black, black, magenta, green);
        int out_w = int(floor(mod(mask_coords.y, 3.0)));
        int out_z = int(floor(mod(mask_coords.x, 4.0)));
        mask_weight = slotmask[out_w * 4 + out_z];
    } else if (phosphor == 4) {
        mask_weight = mix(yellow, blue, floor(mod(mask_coords.x, 2.0)));
    } else if (phosphor == 5) {
        vec3 ap2 = mix(yellow, blue, floor(mod(mask_coords.x, 2.0)));
        vec3 inv_ap2 = mix(blue, yellow, floor(mod(mask_coords.x, 2.0)));
        mask_weight = mix(ap2, inv_ap2, floor(mod(mask_coords.y, 2.0)));
    } else if (phosphor == 6) {
        vec3 ap4[4] = vec3[4](red, green, blue, black);
        int out_z = int(floor(mod(mask_coords.x, 4.0)));
        mask_weight = ap4[out_z];
    } else if (phosphor == 7) {
        vec3 ap3[5] = vec3[5](red, magenta, blue, green, green);
        int out_z = int(floor(mod(mask_coords.x, 5.0)));
        mask_weight = ap3[out_z];
    } else if (phosphor == 8) {
        vec3 big_ap[7] = vec3[7](red, red, yellow, green, cyan, blue, blue);
        int out_w = int(floor(mod(mask_coords.x, 7.0)));
        mask_weight = big_ap[out_w];
    } else if (phosphor == 9) {
        vec3 big_ap_rgb[4] = vec3[4](red, yellow, cyan, blue);
        int out_w = int(floor(mod(mask_coords.x, 4.0)));
        mask_weight = big_ap_rgb[out_w];
    } else if (phosphor == 10) {
        vec3 big_ap_rbg[4] = vec3[4](red, magenta, cyan, green);
        int out_w = int(floor(mod(mask_coords.x, 4.0)));
        mask_weight = big_ap_rbg[out_w];
    } else if (phosphor == 11) {
        vec3 delta1[8] = vec3[8](red, green, blue, black, blue, black, red, green);
        int out_w = int(floor(mod(mask_coords.y, 2.0)));
        int out_z = int(floor(mod(mask_coords.x, 4.0)));
        mask_weight = delta1[out_w * 4 + out_z];
    } else if (phosphor == 12) {
        vec3 delta[8] = vec3[8](red, yellow, cyan, blue, cyan, blue, red, yellow);
        int out_w = int(floor(mod(mask_coords.y, 2.0)));
        int out_z = int(floor(mod(mask_coords.x, 4.0)));
        mask_weight = delta[out_w * 4 + out_z];
    } else if (phosphor == 13) {
        vec3 delta3[16] = vec3[16](red, yellow, cyan, blue, red, yellow, cyan, blue, cyan, blue, red, yellow, cyan, blue, red, yellow);
        int out_w = int(floor(mod(mask_coords.y, 4.0)));
        int out_z = int(floor(mod(mask_coords.x, 4.0)));
        mask_weight = delta3[out_w * 4 + out_z];
    } else if (phosphor == 14) {
        vec3 slotmask14[18] = vec3[18](magenta, green, black, black, black, black, magenta, green, black, magenta, green, black, black, black, black, magenta, green, black);
        int out_w = int(floor(mod(mask_coords.y, 3.0)));
        int out_z = int(floor(mod(mask_coords.x, 6.0)));
        mask_weight = slotmask14[out_w * 6 + out_z];
    } else if (phosphor == 15) {
        vec3 slot2_15[32] = vec3[32](red, yellow, cyan, blue, red, yellow, cyan, blue, red, yellow, cyan, blue, black, black, black, black, red, yellow, cyan, blue, red, yellow, cyan, blue, black, black, black, black, red, yellow, cyan, blue);
        int out_w = int(floor(mod(mask_coords.y, 4.0)));
        int out_z = int(floor(mod(mask_coords.x, 8.0)));
        mask_weight = slot2_15[out_w * 8 + out_z];
    } else if (phosphor == 16) {
        vec3 slotmask16[12] = vec3[12](yellow, blue, black, black, yellow, blue, yellow, blue, black, black, yellow, blue);
        int out_w = int(floor(mod(mask_coords.y, 3.0)));
        int out_z = int(floor(mod(mask_coords.x, 4.0)));
        mask_weight = slotmask16[out_w * 4 + out_z];
    } else if (phosphor == 17) {
        vec3 slot2_17[40] = vec3[40](red, magenta, blue, green, green, red, magenta, blue, green, green, black, blue, blue, green, green, red, red, black, black, black, red, magenta, blue, green, green, red, magenta, blue, green, green, red, red, black, black, black, black, blue, blue, green, green);
        int out_w = int(floor(mod(mask_coords.y, 4.0)));
        int out_z = int(floor(mod(mask_coords.x, 10.0)));
        mask_weight = slot2_17[out_w * 10 + out_z];
    } else if (phosphor == 18) {
        vec3 slot2_18[40] = vec3[40](red, yellow, green, blue, blue, red, yellow, green, blue, blue, black, green, green, blue, blue, red, red, black, black, black, red, yellow, green, blue, blue, red, yellow, green, blue, blue, red, red, black, black, black, black, green, green, blue, blue);
        int out_w = int(floor(mod(mask_coords.y, 4.0)));
        int out_z = int(floor(mod(mask_coords.x, 10.0)));
        mask_weight = slot2_18[out_w * 10 + out_z];
    } else if (phosphor == 19) {
        vec3 slot_19[84] = vec3[84](red, red, yellow, green, cyan, blue, blue, red, red, yellow, green, cyan, blue, blue, red, red, yellow, green, cyan, blue, blue, red, red, yellow, green, cyan, blue, blue, red, red, yellow, green, cyan, blue, blue, black, black, black, black, black, black, black, red, red, yellow, green, cyan, blue, blue, red, red, yellow, green, cyan, blue, blue, red, red, yellow, green, cyan, blue, blue, red, red, yellow, green, cyan, blue, blue, black, black, black, black, black, black, black, black, red, red, yellow, green, cyan, blue);
        int out_w = int(floor(mod(mask_coords.y, 6.0)));
        int out_z = int(floor(mod(mask_coords.x, 14.0)));
        mask_weight = slot_19[out_w * 14 + out_z];
    } else if (phosphor == 20) {
        vec3 tatemask[16] = vec3[16](green, magenta, green, magenta, black, blue, green, red, green, magenta, green, magenta, green, red, black, blue);
        int out_w = int(floor(mod(mask_coords.y, 4.0)));
        int out_z = int(floor(mod(mask_coords.x, 4.0)));
        mask_weight = tatemask[out_w * 4 + out_z];
    } else if (phosphor == 21) {
        vec3 slot_21[32] = vec3[32](red, green, blue, black, red, green, blue, black, red, green, blue, black, black, black, black, black, red, green, blue, black, red, green, blue, black, black, black, black, black, red, green, blue, black);
        int out_w = int(floor(mod(mask_coords.y, 4.0)));
        int out_z = int(floor(mod(mask_coords.x, 8.0)));
        mask_weight = slot_21[out_w * 8 + out_z];
    } else if (phosphor == 22) {
        vec3 bw3[3] = vec3[3](black, white, white);
        int out_z = int(floor(mod(mask_coords.x, 3.0)));
        mask_weight = bw3[out_z];
    } else if (phosphor == 23) {
        vec3 bw4[4] = vec3[4](black, black, white, white);
        int out_z = int(floor(mod(mask_coords.x, 4.0)));
        mask_weight = bw4[out_z];
    } else if (phosphor == 24) {
        vec3 shadow[60] = vec3[60](green, cyan, blue, blue, blue, red, red, red, yellow, green, green, cyan, blue, blue, blue, red, red, red, yellow, green, green, cyan, blue, blue, blue, red, red, red, yellow, green, red, red, red, yellow, green, green, cyan, blue, blue, blue, red, red, red, yellow, green, green, cyan, blue, blue, blue, red, red, red, yellow, green, green, cyan, blue, blue, blue);
        int out_w = int(floor(mod(mask_coords.y, 6.0)));
        int out_z = int(floor(mod(mask_coords.x, 10.0)));
        mask_weight = shadow[out_w * 10 + out_z];
    }

    color.rgb *= mask_weight;
    color = pow(color, vec3(1.0 / OutputGamma, 1.0 / OutputGamma, 1.0 / OutputGamma));
    gl_FragColor = delinearize(vec4(color, 1.0));
}
