// Port of gizmo98 crt shader, generated by mpv-libretro.
// https://github.com/libretro/glsl-shaders/blob/master/crt/shaders/gizmo-crt.glsl
// https://github.com/hhirtz/mpv-retro-shaders/blob/master/gizmo-crt.glsl
//
// Copyright (C) 2023 gizmo98
//
//   This program is free software; you can redistribute it and/or modify it
//   under the terms of the GNU General Public License as published by the Free
//   Software Foundation; either version 2 of the License, or (at your option)
//   any later version.
//
// version 0.41, 01.05.2023
// ---------------------------------------------------------------------------------------
// - add more references for used sources 
//
// version 0.40, 29.04.2023
// ---------------------------------------------------------------------------------------
// - fix aspect ratio issue 
// - fix screen centering issue
// - use CRT/PI curvator
// - add noise intensity value
//
// version 0.35, 29.04.2023
// ---------------------------------------------------------------------------------------
// - initial slang port
// - remove NTSC and INTERLACE effects
// 
// version 0.3, 28.04.2023
// ---------------------------------------------------------------------------------------
// - unify shader in one file
// - replace fixed macros and defines with pragmas
// - add BLUR_OFFSET setting. This setting can be used to set the strength of a bad signal
// - add ANAMORPH setting for megadrive and snes
// 
// https://github.com/gizmo98/gizmo-crt-shader
//
// This shader tries to mimic a CRT without extensive use of scanlines and rgb pattern emulation.
// It uses horizontal subpixel scaling and adds brightness dependent scanline patterns and allows 
// fractional scaling. 
//
// HORIZONTAL_BLUR simulates a bad composite signal which is neede for consoles like megadrive 
// VERTICAL_BLUR vertical blur simulates N64 vertical blur 
// BGR_LCD_PATTERN most LCDs have a RGB pixel pattern. Enable BGR pattern with this switch
// BRIGHTNESS makes scanlines more or less visible
// SHRINK scale screen in X direction
// SNR noise intensity 
//
// uses parts curvator of CRT-PI shader from davej https://github.com/libretro/glsl-shaders/blob/master/crt/shaders/crt-pi.glsl
// uses parts of texture anti-aliasing shader from Ikaros https://www.shadertoy.com/view/ldsSRX
// uses gold noise shader from dcerisano https://www.shadertoy.com/view/ltB3zD

[vertex]
attribute vec2 a_position;
attribute vec2 a_texcoords;

varying vec2 v_texcoords;

void main()
{
    v_texcoords = a_texcoords;
    gl_Position = vec4(a_position, 0.0, 1.0);
}

[fragment]
uniform sampler2D u_texture;
uniform vec2 u_screenSize;

varying vec2 v_texcoords;

#define CURVATURE_X 0.1
#define CURVATURE_Y 0.15
#define BRIGHTNESS 0.5
#define HORIZONTAL_BLUR 0.0
#define VERTICAL_BLUR 0.0
#define BLUR_OFFSET 0.5
#define BGR_LCD_PATTERN 0.0
#define SHRINK 0.0

vec4 linearize(vec4 color)
{
    const float _const_0_1 = 0.05958483740687370300;
    const float _const_1_1 = 0.87031054496765136718;
    color.rgb = max(color.rgb, 0.0);
    color.rgb = _const_1_1 * pow(color.rgb + vec3(_const_0_1), vec3(2.4));
    return color;
}

vec4 delinearize(vec4 color)
{
    const float _const_0_2 = 0.05958483740687370300;
    const float _const_1_2 = 1.14901518821716308593;
    color.rgb = max(color.rgb, 0.0);
    color.rgb = pow(_const_1_2 * color.rgb, vec3(1.0/2.4)) - vec3(_const_0_2);
    return color;
}

float PHI = 1.618034;

float gold_noise(in vec2 xy, in float seed)
{
    return fract(tan(distance(xy * PHI, xy) * seed) * xy.x);
}

vec2 saturateA(in vec2 x)
{
    return clamp(x, 0.0, 1.0);
}

vec2 magnify(in vec2 uv, in vec2 res)
{
    uv *= res;
    return (saturateA(fract(uv) / saturateA(fwidth(uv))) + floor(uv) - 0.5) / res.xy;
}

vec4 textureVertical(in vec2 uv)
{
    vec2 texSize = u_screenSize;
    uv = magnify(uv, texSize.xy);
    uv = uv * texSize.xy + 0.5;
    vec2 iuv = floor(uv);
    vec2 fuv = uv - iuv;
    if (HORIZONTAL_BLUR == 1.0) {
        vec2 uv1 = vec2(uv + vec2(-0.5, -0.5)) / texSize.xy;
        vec2 uv2 = vec2(uv + vec2(-0.5 + BLUR_OFFSET, -0.5)) / texSize.xy;
        vec4 col1 = linearize(texture2D(u_texture, uv1));
        vec4 col2 = linearize(texture2D(u_texture, uv2));
        vec4 col = (col1 + col2) / vec4(2.0);
        if (VERTICAL_BLUR == 1.0) {
            vec2 uv3 = vec2(uv + vec2(-0.5, -0.5 + BLUR_OFFSET)) / texSize.xy;
            vec2 uv4 = vec2(uv + vec2(-0.5 + BLUR_OFFSET, -0.5 + BLUR_OFFSET)) / texSize.xy;
            vec4 col3 = linearize(texture2D(u_texture, uv3));
            vec4 col4 = linearize(texture2D(u_texture, uv4));
            col = ((col3 + col4) / vec4(2.0) + col) / vec4(2.0);
        }
        return col;
    } else {
        uv = vec2(uv + vec2(-0.5, -0.5)) / texSize.xy;
        return linearize(texture2D(u_texture, uv));
    }
}

vec4 textureCRT(in vec2 uvr, in vec2 uvg, in vec2 uvb)
{
    return vec4(textureVertical(uvr).r, textureVertical(uvg).g, textureVertical(uvb).b, 255.0);
}

float GetFuv(in vec2 uv)
{
    vec2 texSize = u_screenSize;
    uv = uv * texSize.xy + 0.5;
    vec2 iuv = floor(uv);
    vec2 fuv = uv - iuv;
    return abs((fuv * fuv * fuv * (fuv * (fuv * 6.0 - 15.0) + 10.0)).y - 0.5);
}

vec2 GetIuv(in vec2 uv)
{
    vec2 texSize = u_screenSize;
    uv = uv * texSize.xy;
    vec2 iuv = floor(uv);
    return iuv;
}

vec4 AddNoise(in vec4 col, in vec2 coord)
{
    float iGlobalTime = 0.0;
    return clamp(col + gold_noise(coord, sin(iGlobalTime)) / 32.0 - 1.0 / 64.0, 0.0, 1.0);
}

vec4 AddScanlines(in vec4 col, in vec2 coord)
{
    vec2 texSize = u_screenSize;
    float brightness = 1.0 / BRIGHTNESS * 0.05;
    float scale = u_screenSize.y / texSize.y * 0.5;
    float dim = brightness * scale;
    col.rgb -= dim * abs(1.5 * (1.0 - col.rgb) * abs(abs(GetFuv(coord) - 0.5)));
    return col;
}

vec3 XCoords(in float coord, in float factor)
{
    float iGlobalTime = 0.0;
    float spread = 0.333;
    vec3 coords = vec3(coord);
    if (BGR_LCD_PATTERN == 1.0) coords.r += spread * 2.0; else coords.b += spread * 2.0;
    coords.g += spread;
    coords *= factor;
    return coords;
}

float YCoord(in float coord, in float factor)
{
    return coord * factor;
}

vec2 CURVATURE_DISTORTION = vec2(CURVATURE_X, CURVATURE_Y);
vec2 barrelScale = 1.0 - 0.23 * CURVATURE_DISTORTION;

vec2 Distort(vec2 coord)
{
    coord -= vec2(0.5);
    float rsq = coord.x * coord.x + coord.y * coord.y;
    coord += coord * (CURVATURE_DISTORTION * rsq);
    coord *= barrelScale;
    if (abs(coord.x) >= 0.5 || abs(coord.y) >= 0.5) coord = vec2(-1.0); else {
        coord += vec2(0.5);
    }
    return coord;
}

void main()
{
    vec2 texSize = u_screenSize;
    vec2 texcoord = v_texcoords.xy;
    if (SHRINK > 0.0) {
        texcoord.y -= 0.5;
        texcoord.y *= 1.0 + SHRINK;
        texcoord.y += 0.5;
    }
    texcoord = Distort(texcoord);
    if (texcoord.x < 0.0) {
        gl_FragColor = vec4(0.0);
        return;
    }
    vec2 fragCoord = texcoord.xy * u_screenSize;
    vec2 factor = texSize.xy / u_screenSize;
    float yCoord = YCoord(fragCoord.y, factor.y);
    vec3 xCoords = XCoords(fragCoord.x, factor.x);
    vec2 coord_r = vec2(xCoords.r / texSize.x, texcoord.y);
    vec2 coord_g = vec2(xCoords.g, yCoord) / texSize.xy;
    vec2 coord_b = vec2(xCoords.b, yCoord) / texSize.xy;
    vec4 color = textureCRT(coord_r, coord_g, coord_b);
    color = AddNoise(color, fragCoord);
    color = AddScanlines(color, coord_r);
    color.a = 1.0;
    gl_FragColor = delinearize(color);
}
