// Port of CRT Guest Nomask w. Curvature (crt-gdv-mini-ultra.slang), generated by mpv-libretro
// https://github.com/libretro/slang-shaders/blob/4ab9e232f3406b9932c5b6159e4315dd1734a162/crt/shaders/crt-gdv-mini-ultra.slang
// https://github.com/hhirtz/mpv-retro-shaders/blob/master/crt-gdv-mini-ultra-trinitron.glsl
//
// CRT - Guest - Nomask w. Curvature
// With work by DariusG to create a cut down extra fast version
// 
// Copyright (C) 2017-2018 guest(r) - guest.r@gmail.com
// 
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

[vertex]
attribute vec2 a_position;
attribute vec2 a_texcoords;

varying vec2 v_texcoords;

void main()
{
    v_texcoords = a_texcoords;
    gl_Position = vec4(a_position, 0.0, 1.0);
}

[fragment]
uniform sampler2D u_texture;
uniform vec2 u_screenSize;

varying vec2 v_texcoords;

#define CGWG 1.0
#define beam_max 2.0
#define beam_min 1.5
#define brightboost 1.2
#define gamma_out_blue 2.2
#define gamma_out_green 2.2
#define gamma_out_red 2.2
#define gdv_B 1.0
#define gdv_G 1.0
#define gdv_R 1.0
#define gdv_mono 0.0
#define glow 0.35
#define h_sharp 2.5
#define maskDark 0.0
#define maskLight 1.5
#define masksize 1.0
#define mcut 0.2
#define sat 1.2
#define scanline 10.0
#define shadowMask 11.0
#define thres 0.4
#define vignette 1.0
#define warpX 0.0
#define warpY 0.05

vec4 linearize(vec4 color)
{
    const float _const_0_1 = 0.05958483740687370300;
    const float _const_1_1 = 0.87031054496765136718;
    color.rgb = max(color.rgb, 0.0);
    color.rgb = _const_1_1 * pow(color.rgb + vec3(_const_0_1), vec3(2.4));
    return color;
}

vec4 delinearize(vec4 color)
{
    const float _const_0_2 = 0.05958483740687370300;
    const float _const_1_2 = 1.14901518821716308593;
    color.rgb = max(color.rgb, 0.0);
    color.rgb = pow(_const_1_2 * color.rgb, vec3(1.0/2.4)) - vec3(_const_0_2);
    return color;
}

float sw_func(float x, float l)
{
    float d = x;
    float bm = scanline;
    float b = mix(beam_min, beam_max, l);
    d = exp2(-bm * pow(d, b));
    return d;
}

vec3 toGrayscale(vec3 color)
{
    float average = (color.r + color.g + color.b) / 3.0;
    return vec3(average);
}

vec3 colorize(vec3 grayscale, vec3 color)
{
    return grayscale * color;
}

vec3 Mask(vec2 pos, vec3 c)
{
    pos = floor(pos / masksize);
    vec3 mask = vec3(maskDark, maskDark, maskDark);
    if (shadowMask == -1.0) {
        mask = vec3(1.0);
    } else if (shadowMask == 0.0) {
        pos.x = fract(pos.x * 0.5);
        float mc = 1.0 - CGWG;
        if (pos.x < 0.5) {
            mask.r = 1.1;
            mask.g = mc;
            mask.b = 1.1;
        } else {
            mask.r = mc;
            mask.g = 1.1;
            mask.b = mc;
        }
    } else if (shadowMask == 1.0) {
        float line = maskLight;
        float odd = 0.0;
        if (fract(pos.x / 6.0) < 0.5) odd = 1.0;
        if (fract((pos.y + odd) / 2.0) < 0.5) line = maskDark;
        pos.x = fract(pos.x / 3.0);
        if (pos.x < 0.333) mask.b = maskLight; else if (pos.x < 0.666) mask.g = maskLight; else mask.r = maskLight;
        mask *= line;
    } else if (shadowMask == 2.0) {
        pos.x = fract(pos.x / 3.0);
        if (pos.x < 0.333) mask.b = maskLight; else if (pos.x < 0.666) mask.g = maskLight; else mask.r = maskLight;
    } else if (shadowMask == 3.0) {
        pos.x += pos.y * 3.0;
        pos.x = fract(pos.x / 6.0);
        if (pos.x < 0.333) mask.b = maskLight; else if (pos.x < 0.666) mask.g = maskLight; else mask.r = maskLight;
    } else if (shadowMask == 4.0) {
        pos.xy = floor(pos.xy * vec2(1.0, 0.5));
        pos.x += pos.y * 3.0;
        pos.x = fract(pos.x / 6.0);
        if (pos.x < 0.333) mask.b = maskLight; else if (pos.x < 0.666) mask.g = maskLight; else mask.r = maskLight;
    } else if (shadowMask == 5.0) {
        float mx = max(max(c.r, c.g), c.b);
        vec3 maskTmp = vec3(min(1.25 * max(mx - mcut, 0.0) / (1.0 - mcut), maskDark + 0.2 * (1.0 - maskDark) * mx));
        float adj = 0.8 * maskLight - 0.5 * (0.8 * maskLight - 1.0) * mx + 0.75 * (1.0 - mx);
        mask = maskTmp;
        pos.x = fract(pos.x / 2.0);
        if (pos.x < 0.5) {
            mask.r = adj;
            mask.b = adj;
        } else mask.g = adj;
    } else if (shadowMask == 6.0) {
        float mx = max(max(c.r, c.g), c.b);
        vec3 maskTmp = vec3(min(1.33 * max(mx - mcut, 0.0) / (1.0 - mcut), maskDark + 0.225 * (1.0 - maskDark) * mx));
        float adj = 0.8 * maskLight - 0.5 * (0.8 * maskLight - 1.0) * mx + 0.75 * (1.0 - mx);
        mask = maskTmp;
        pos.x = fract(pos.x / 3.0);
        if (pos.x < 0.333) mask.r = adj; else if (pos.x < 0.666) mask.g = adj; else mask.b = adj;
    } else if (shadowMask == 7.0) {
        float mc = 1.0 - CGWG;
        float mx = max(max(c.r, c.g), c.b);
        float maskTmp = min(1.6 * max(mx - mcut, 0.0) / (1.0 - mcut), mc);
        mask = vec3(maskTmp);
        pos.x = fract(pos.x / 2.0);
        if (pos.x < 0.5) mask = vec3(1.0 + 0.6 * (1.0 - mx));
    } else if (shadowMask == 8.0) {
        float line = maskLight;
        float odd = 0.0;
        if (fract(pos.x / 4.0) < 0.5) odd = 1.0;
        if (fract((pos.y + odd) / 2.0) < 0.5) line = maskDark;
        pos.x = fract(pos.x / 2.0);
        if (pos.x < 0.5) {
            mask.r = maskLight;
            mask.b = maskLight;
        } else mask.g = maskLight;
        mask *= line;
    } else if (shadowMask == 9.0) {
        vec3 result = vec3(maskDark);
        float bright = maskLight;
        float left = 0.0;
        if (fract(pos.x / 6.0) < 0.5) left = 1.0;
        float m = fract(pos.x / 3.0);
        if (m < 0.3333) result.b = 0.9; else if (m < 0.6666) result.g = 0.9; else result.r = 0.9;
        if (mod(pos.y, 2.0) == 1.0 && left == 1.0 || mod(pos.y, 2.0) == 0.0 && left == 0.0) result *= bright;
        return result;
    } else if (shadowMask == 10.0) {
        vec3 result = vec3(maskDark);
        float line = maskLight;
        float odd = 0.0;
        if (fract(pos.x / 6.0) < 0.5) odd = 1.0;
        if (fract((pos.y + odd) / 2.0) < 0.5) line = 1.0;
        float m = fract(pos.x / 3.0);
        float y = fract(pos.y / 2.0);
        if (m > 0.3333) {
            result.r = 1.0;
            result.b = 1.0;
        } else if (m > 0.6666) result.g = 1.0; else result = vec3(mcut);
        if (m > 0.333) result *= line;
        return result;
    } else if (shadowMask == 11.0) {
        vec3 result = vec3(maskDark);
        pos.x = fract(pos.x / 3.0);
        if (pos.x > 0.333) result = vec3(1.0);
        return result;
    }
    return mask;
}

mat3 vign_func(float l)
{
    vec2 vpos = v_texcoords;
    vpos *= 1.0 - vpos.xy;
    float vig = vpos.x * vpos.y * 45.0;
    vig = min(pow(vig, 0.15), 1.0);
    if (vignette == 0.0) vig = 1.0;
    return mat3(vig, 0, 0, 0, vig, 0, 0, 0, vig);
}

vec2 Warp(vec2 pos)
{
    pos = pos * 2.0 - 1.0;
    pos *= vec2(1.0 + pos.y * pos.y * warpX, 1.0 + pos.x * pos.x * warpY);
    return pos * 0.5 + 0.5;
}

vec3 saturation_func(vec3 textureColor)
{
    float lum = length(textureColor.rgb) * 0.5775;
    vec3 luminanceWeighting = vec3(0.3, 0.6, 0.1);
    if (lum < 0.5) luminanceWeighting.rgb = luminanceWeighting.rgb * luminanceWeighting.rgb + luminanceWeighting.rgb * luminanceWeighting.rgb;
    float luminance = dot(textureColor.rgb, luminanceWeighting);
    vec3 greyScaleColor = vec3(luminance);
    vec3 color1 = vec3(mix(greyScaleColor, textureColor.rgb, sat));
    return color1;
}

vec3 glow_func(vec2 texcoord, vec3 col)
{
    vec3 sum = vec3(0.0);
    vec2 blurSize = 1.0 / u_screenSize;
    vec3 c20 = linearize(texture2D(u_texture, vec2(texcoord.x - 2.0 * blurSize.x, texcoord.y))).rgb;
    vec3 c10 = linearize(texture2D(u_texture, vec2(texcoord.x - blurSize.x, texcoord.y))).rgb;
    vec3 c11 = linearize(texture2D(u_texture, vec2(texcoord.x, texcoord.y))).rgb;
    vec3 c12 = linearize(texture2D(u_texture, vec2(texcoord.x + blurSize.x, texcoord.y))).rgb;
    vec3 c21 = linearize(texture2D(u_texture, vec2(texcoord.x + 2.0 * blurSize.x, texcoord.y))).rgb;
    vec3 c22 = linearize(texture2D(u_texture, vec2(texcoord.x - 2.0 * blurSize.x, texcoord.y - blurSize.y))).rgb;
    vec3 c23 = linearize(texture2D(u_texture, vec2(texcoord.x - blurSize.x, texcoord.y - 2.0 * blurSize.y))).rgb;
    vec3 c13 = linearize(texture2D(u_texture, vec2(texcoord.x - blurSize.x, texcoord.y - blurSize.y))).rgb;
    vec3 c14 = linearize(texture2D(u_texture, vec2(texcoord.x + blurSize.x, texcoord.y + blurSize.y))).rgb;
    vec3 c24 = linearize(texture2D(u_texture, vec2(texcoord.x + blurSize.x, texcoord.y + 2.0 * blurSize.y))).rgb;
    vec3 c25 = linearize(texture2D(u_texture, vec2(texcoord.x + 2.0 * blurSize.x, texcoord.y + blurSize.y))).rgb;
    vec3 c26 = linearize(texture2D(u_texture, vec2(texcoord.x - 2.0 * blurSize.x, texcoord.y + blurSize.y))).rgb;
    vec3 c27 = linearize(texture2D(u_texture, vec2(texcoord.x - blurSize.x, texcoord.y + 2.0 * blurSize.y))).rgb;
    vec3 c15 = linearize(texture2D(u_texture, vec2(texcoord.x - blurSize.x, texcoord.y + blurSize.y))).rgb;
    vec3 c16 = linearize(texture2D(u_texture, vec2(texcoord.x + blurSize.x, texcoord.y - blurSize.y))).rgb;
    vec3 c28 = linearize(texture2D(u_texture, vec2(texcoord.x + blurSize.x, texcoord.y - 2.0 * blurSize.y))).rgb;
    vec3 c29 = linearize(texture2D(u_texture, vec2(texcoord.x + 2.0 * blurSize.x, texcoord.y - blurSize.y))).rgb;
    vec3 c30 = linearize(texture2D(u_texture, vec2(texcoord.x, texcoord.y - 2.0 * blurSize.y))).rgb;
    vec3 c17 = linearize(texture2D(u_texture, vec2(texcoord.x, texcoord.y - blurSize.y))).rgb;
    vec3 c18 = linearize(texture2D(u_texture, vec2(texcoord.x, texcoord.y + blurSize.y))).rgb;
    vec3 c31 = linearize(texture2D(u_texture, vec2(texcoord.x, texcoord.y + 2.0 * blurSize.y))).rgb;
    sum = (3.0 * c11 + 2.5 * (c10 + c12 + c13 + c14 + c15 + c16 + c17 + c18) + 1.5 * (c20 + c21 + c22 + c23 + c24 + c25 + c26 + c27 + c28 + c29 + c30 + c31)) / 45.0;
    return sum * glow;
}

void main()
{
    vec2 tc = v_texcoords * 1.0001;
    vec2 pos = Warp(tc);
    vec2 ps = 1.0 / u_screenSize;
    vec2 OGL2Pos = pos * u_screenSize;
    vec2 fp = fract(OGL2Pos);
    vec2 dx = vec2(ps.x, 0.0);
    vec2 dy = vec2(0.0, ps.y);
    vec2 pC4 = floor(OGL2Pos) * ps + 0.5 * ps;
    vec3 ul = linearize(texture2D(u_texture, pC4)).xyz;
    vec3 ur = linearize(texture2D(u_texture, pC4 + dx)).xyz;
    vec3 dl = linearize(texture2D(u_texture, pC4 + dy)).xyz;
    vec3 dr = linearize(texture2D(u_texture, pC4 + ps)).xyz;
    float lx = fp.x;
    lx = pow(lx, h_sharp);
    float rx = 1.0 - fp.x;
    rx = pow(rx, h_sharp);
    vec3 color1 = (ur * lx + ul * rx) / (lx + rx);
    vec3 color2 = (dr * lx + dl * rx) / (lx + rx);
    float f = fp.y;
    float luma1 = color1.r * 0.3 + color1.g * 0.6 + color1.b * 0.1;
    float luma2 = color2.r * 0.3 + color2.g * 0.6 + color2.b * 0.1;
    color1 = 2.0 * pow(color1, vec3(2.8)) - pow(color1, vec3(3.6));
    color2 = 2.0 * pow(color2, vec3(2.8)) - pow(color2, vec3(3.6));
    color1 = color1 * mix(Mask(tc * u_screenSize, color1), vec3(1.0), luma1 * thres);
    color2 = color2 * mix(Mask(tc * u_screenSize, color2), vec3(1.0), luma2 * thres);
    vec3 color = color1 * sw_func(f, luma1) + color2 * sw_func(1.0 - f, luma2);
    if (u_screenSize.y >= 400.0) {
        color = (color1 + color2) / 2.0;
    }
    color = min(color, 1.0);
    float lum = color.r * 0.3 + color.g * 0.6 + color.b * 0.1;
    color = pow(color, vec3(1.0 / gamma_out_red, 1.0, 1.0));
    color = pow(color, vec3(1.0, 1.0 / gamma_out_green, 1.0));
    color = pow(color, vec3(1.0, 1.0, 1.0 / gamma_out_blue));
    color += glow_func(pC4, color);
    color *= mix(1.0, brightboost, lum);
    color = saturation_func(color);
    color *= vign_func(lum);
    if (gdv_mono == 1.0) {
        vec3 col1 = toGrayscale(color);
        vec3 c = vec3(gdv_R, gdv_G, gdv_B);
        color = colorize(col1, c);
    }
    gl_FragColor = delinearize(vec4(color, 1.0));
}
