require("api/entity/missileWeaponData.lua")

MissileWeaponData()
    :setName("Homing")
    :setLocaleName(_("missile", "Homing"))
    :setOrder(0)
    :setSpeed(200)
    :setTurnrate(10)
    :setLifetime(27)
    :setColor(255, 200, 0, 255)
    :setHomingRange(1200)
    :setFireSound("sfx/rlaunch.wav")
    :setRadarTrace("radar/missile.png")
    :setDamageAtCenter(35)
    :setDamageAtEdge(5)
    :setBlastRange(30)
    :setExplosionSfx("sfx/explosion.wav")
    :setRadarSignature(0.0, 0.1, 0.2)

MissileWeaponData()
    :setName("Nuke")
    :setLocaleName(_("missile", "Nuke"))
    :setOrder(1)
    :setSpeed(200)
    :setTurnrate(10)
    :setLifetime(27)
    :setColor(255, 100, 32, 255)
    :setHomingRange(500)
    :setFireSound("sfx/rlaunch.wav")
    :setRadarTrace("radar/missile.png")
    :setDamageAtCenter(160)
    :setDamageAtEdge(30)
    :setBlastRange(1000)
    :setExplosionSfx("sfx/nuke_explosion.wav")
    :setRadarSignature(0.0, 0.7, 0.1)
    :setExplodesOnTimeout(true)
    :setAvoidObjectDelay(10)

MissileWeaponData()
    :setName("Mine")
    :setLocaleName(_("missile", "Mine"))
    :setOrder(2)
    :setSpeed(100)
    :setTurnrate(0)
    :setLifetime(10)
    :setColor(255, 255, 255, 255)
    :setHomingRange(0)
    :setFireSound("sfx/missile_launch.wav")
    :setRadarTrace("radar/mine.png")
    :setDamageAtCenter(160)
    :setDamageAtEdge(30)
    :setBlastRange(1000)
    :setExplosionSfx("sfx/explosion.wav")
    :setRadarSignature(0.0, 0.05, 0.0)
    :setIsDelayedExplode(true)
    :setAvoidObjectDelay(0)
    :setCircleCollision(true)
    :setNoLifetimeOnMissile(true)
    :setFireCount(1)

MissileWeaponData()
    :setName("EMP")
    :setLocaleName(_("missile", "EMP"))
    :setOrder(3)
    :setSpeed(200)
    :setTurnrate(10)
    :setLifetime(27)
    :setColor(100, 32, 255, 255)
    :setHomingRange(500)
    :setFireSound("sfx/rlaunch.wav")
    :setRadarTrace("radar/missile.png")
    :setDamageAtCenter(160)
    :setDamageAtEdge(30)
    :setBlastRange(1000)
    :setExplosionSfx("sfx/emp_explosion.wav")
    :setRadarSignature(0.0, 1.0, 0.0)
    :setExplodesOnTimeout(true)
    :setDamageType("EMP")

MissileWeaponData()
    :setName("HVLI")
    :setLocaleName(_("missile", "HVLI"))
    :setOrder(4)
    :setSpeed(500)
    :setTurnrate(0)
    :setLifetime(13.5)
    :setColor(128, 128, 128, 255)
    :setHomingRange(0)
    :setFireSound("sfx/hvli_fire.wav")
    :setRadarTrace("radar/missile.png")
    :setDamageAtCenter(10)
    :setDamageAtEdge(10)
    :setBlastRange(20)
    :setExplosionSfx("sfx/explosion.wav")
    :setRadarSignature(0.1, 0.0, 0.0)
    :setFireCount(5)
