--[[ Cruisers

Cruisers are large capital ships, dwarfed only by battleships. Particularly large cruisers are also known as battlecruisers.

What cruisers lose in agility compared to destroyers, they gain in armor and weaponry. A cruiser bristling with weapon tubes or beam weapons can cleave through even large space stations in short order if not countered by a coordinated, focused defense.
]]

-- Vindicator (Player Cruiser)
local template = ShipTemplate()
    :setName("Vindicator")
    :setLocaleName(_("playerShip", "Vindicator"))
    :setModel("battleship_destroyer_2_upgraded")
    :setClass(_("class", "Cruiser"), _("subclass", "Assault"))
    :setType("playership")
    :setRadarTrace("cruiser.png")
    :setDescription(
        _(
            [[The fearsome Vindicator cruiser hull balances stout armor and forward-facing weapons with a tremendous impulse engine, which grants it the sublight speed of a pursuer even if it lacks the turning rate of a smaller craft.

A skilled navigator and helms officer can use the Vindicator's jump drive and impulse engine to appear at missile range, launch an array of missiles as powerful as nuclear weapons, and then outrun defenders in a race while its jump drive recharges. Its combat thrusters aid as much in its defensive maneuverability as it does to close in on fleeing targets.]]
        )
    )
    :setBeam(0, 90, -15, 1000.0, 6.0, 10)
    :setBeam(1, 90, 15, 1000.0, 6.0, 10)
    :setTubes(3, 8.0)
    :setTubeDirection(0, -5)
    :weaponTubeDisallowMissle(0, "Mine")
    :setTubeDirection(1, 5)
    :weaponTubeDisallowMissle(1, "Mine")
    :setTubeDirection(2, 180)
    :setWeaponTubeExclusiveFor(2, "Mine")
    :setHull(200)
    :setShields(80, 80)
    :setSpeed(90, 10, 20)
    :setJumpDrive(true)
    :setCombatManeuver(400, 250)
    :setWeaponStorage("Homing", 12)
    :setWeaponStorage("Nuke", 4)
    :setWeaponStorage("Mine", 8)
    :setWeaponStorage("EMP", 6)
    :addRoomSystem(1, 0, 2, 1, "Maneuver")
    :addRoomSystem(1, 1, 2, 1, "BeamWeapons")
    :addRoomSystem(2, 2, 2, 1, "DockingBay")
    :addRoomSystem(0, 3, 1, 2, "RearShield")
    :addRoomSystem(1, 3, 2, 2, "Reactor")
    :addRoomSystem(3, 3, 2, 2, "Warp")
    :addRoomSystem(5, 3, 1, 2, "JumpDrive")
    :addRoomSystem(6, 3, 2, 1, "Sensors")
    :addRoom(6, 4, 2, 1)
    :addRoomSystem(8, 3, 1, 2, "FrontShield")
    :addRoom(2, 5, 2, 1)
    :addRoomSystem(1, 6, 2, 1, "MissileSystem")
    :addRoomSystem(1, 7, 2, 1, "Impulse")
    :addDoor(1, 1, true)
    :addDoor(2, 2, true)
    :addDoor(3, 3, true)
    :addDoor(1, 3, false)
    :addDoor(3, 4, false)
    :addDoor(3, 5, true)
    :addDoor(2, 6, true)
    :addDoor(1, 7, true)
    :addDoor(5, 3, false)
    :addDoor(6, 3, false)
    :addDoor(6, 4, false)
    :addDoor(8, 3, false)
    :addDoor(8, 4, false)

--Airlock doors
--template:addDoor(2, 2, false);
--template:addDoor(2, 5, false);

-- Avalanche (Player Missile Cr.)
template = ShipTemplate()
    :setName("Avalanche")
    :setLocaleName(_("playerShip", "Avalanche"))
    :setModel("space_cruiser_4")
    :setClass(_("class", "Cruiser"), _("subclass", "Bombardment"))
    :setType("playership")
    :setRadarTrace("missile_cruiser.png")
    :setDescription(
        _(
            [[The Avalanche cruiser is a warp-capable, missile-laden vessel that carries enough munitions on its own to level a system full of space stations. Its 6 missile tubes cover all but its rear angles, which houses a mine-laying tube.

The Avalanche earned its moniker for being unstoppable, but also for being spotted from sectors away as it races into position. If not covered by escorts, its vulnerable rear shields and slow maneuverability can leave it prey to smaller ships that don't fear it on sight.]]
        )
    )
    :setTubes(7, 8.0)
    :setTubeDirection(0, 0)
    :weaponTubeDisallowMissle(0, "Mine")
    :setTubeDirection(1, 0)
    :weaponTubeDisallowMissle(1, "Mine")
    :setTubeDirection(2, 90)
    :setWeaponTubeExclusiveFor(2, "Homing")
    :setTubeDirection(3, 90)
    :setWeaponTubeExclusiveFor(3, "Homing")
    :setTubeDirection(4, -90)
    :setWeaponTubeExclusiveFor(4, "Homing")
    :setTubeDirection(5, -90)
    :setWeaponTubeExclusiveFor(5, "Homing")
    :setTubeDirection(6, 180)
    :setWeaponTubeExclusiveFor(6, "Mine")
    :setHull(200)
    :setShields(110, 70)
    :setSpeed(60, 8, 15)
    :setCombatManeuver(450, 150)
    :setWarpSpeed(800)
    :setJumpDrive(false)
    :setWeaponStorage("Homing", 30)
    :setWeaponStorage("Nuke", 8)
    :setWeaponStorage("Mine", 12)
    :setWeaponStorage("EMP", 10)
    :addRoomSystem(1, 0, 2, 1, "Maneuver")
    :addRoomSystem(1, 1, 2, 1, "BeamWeapons")
    :addRoomSystem(2, 2, 2, 1, "DockingBay")
    :addRoomSystem(0, 3, 1, 2, "RearShield")
    :addRoomSystem(1, 3, 2, 2, "Reactor")
    :addRoomSystem(3, 3, 2, 2, "Warp")
    :addRoomSystem(5, 3, 1, 2, "JumpDrive")
    :addRoomSystem(6, 3, 2, 1, "Sensors")
    :addRoom(6, 4, 2, 1)
    :addRoomSystem(8, 3, 1, 2, "FrontShield")
    :addRoom(2, 5, 2, 1)
    :addRoomSystem(1, 6, 2, 1, "MissileSystem")
    :addRoomSystem(1, 7, 2, 1, "Impulse")
    :addDoor(1, 1, true)
    :addDoor(2, 2, true)
    :addDoor(3, 3, true)
    :addDoor(1, 3, false)
    :addDoor(3, 4, false)
    :addDoor(3, 5, true)
    :addDoor(2, 6, true)
    :addDoor(1, 7, true)
    :addDoor(5, 3, false)
    :addDoor(6, 3, false)
    :addDoor(6, 4, false)
    :addDoor(8, 3, false)
    :addDoor(8, 4, false)

-- Battlestation
template = ShipTemplate()
    :setName("Battlestation")
    :setLocaleName(_("ship", "Battlestation"))
    :setModel("Ender Battlecruiser")
    :setClass(_("class", "Battlecruiser"), _("subclass", "Superiority"))
    :setRadarTrace("battleship.png")
    :setDescription(
        _(
            [[The Battlestation is a battlecruiser with a dozen beam emplacements, a jump drive, and docking clamps to carry ships as large as frigates on its exterior into battle. Its offensive capabilities are offset by a single, if powerful, shield generator and a relatively fragile hull for a vessel its size.

Battlestations are meant to join large-fleet ambushes, drop their docked vessels, provide coverage against retaliating starfighters, and then jump out the moment the tide of battle turns in their favor. However, a barrage of EMPs and HVLIs can quickly whittle it down.]]
        )
    )
    :setBeam(0, 120, -90, 2500.0, 6.1, 4)
    :setBeam(1, 120, -90, 2500.0, 6.0, 4)
    :setBeam(2, 120, 90, 2500.0, 6.1, 4)
    :setBeam(3, 120, 90, 2500.0, 6.0, 4)
    :setBeam(4, 120, -90, 2500.0, 5.9, 4)
    :setBeam(5, 120, -90, 2500.0, 6.2, 4)
    :setBeam(6, 120, 90, 2500.0, 5.9, 4)
    :setBeam(7, 120, 90, 2500.0, 6.2, 4)
    :setBeam(8, 120, -90, 2500.0, 6.1, 4)
    :setBeam(9, 120, -90, 2500.0, 6.0, 4)
    :setBeam(10, 120, 90, 2500.0, 6.1, 4)
    :setBeam(11, 120, 90, 2500.0, 6.0, 4)
    :setHull(100)
    :setShields(2500)
    :setSpeed(20, 1.5, 3)
    :setJumpDrive(true)
    :setExternalDockClasses(
        _("class", "Corvette"),
        _("class", "Frigate")
    )
    :setInternalDockClasses(
        _("class", "Cargo"),
        _("class", "Starfighter"),
        _("class", "Tug"),
        _("class", "Transport")
    )
    :setSharesEnergyWithDocked(true)

-- Ender (PlayerControl variant)
variation = template
    :copy("Ender")
    :setType("playership")
    :setLocaleName(_("playerShip", "Ender"))
variation:setDescription(
        _(
            [[The Ender revision to the Battlestation divided its shields into two smaller generators, which opened space for more capable impulse engines and thrusters. These changes grant it surprising agility for a capital ship, although it still handles much differently than a destroyer.

The Ender's revisions also made space to install 2 weapon tubes, one dedicated to laying mines in order to deter pursuing capital ships and immediately secure territory that it helped win.]]
        )
    )
    :setBeam(0, 10, -90, 2500.0, 6.1, 4)
    :setBeam(1, 10, -90, 2500.0, 6.0, 4)
    :setBeam(2, 10, 90, 2500.0, 5.8, 4)
    :setBeam(3, 10, 90, 2500.0, 6.3, 4)
    :setBeam(4, 10, -90, 2500.0, 5.9, 4)
    :setBeam(5, 10, -90, 2500.0, 6.4, 4)
    :setBeam(6, 10, 90, 2500.0, 5.7, 4)
    :setBeam(7, 10, 90, 2500.0, 5.6, 4)
    :setBeam(8, 10, -90, 2500.0, 6.6, 4)
    :setBeam(9, 10, -90, 2500.0, 5.5, 4)
    :setBeam(10, 10, 90, 2500.0, 6.5, 4)
    :setBeam(11, 10, 90, 2500.0, 6.2, 4)
    :setBeamWeaponTurret(0, 120, -90, 6)
    :setBeamWeaponTurret(1, 120, -90, 6)
    :setBeamWeaponTurret(2, 120, 90, 6)
    :setBeamWeaponTurret(3, 120, 90, 6)
    :setBeamWeaponTurret(4, 120, -90, 6)
    :setBeamWeaponTurret(5, 120, -90, 6)
    :setBeamWeaponTurret(6, 120, 90, 6)
    :setBeamWeaponTurret(7, 120, 90, 6)
    :setBeamWeaponTurret(8, 120, -90, 6)
    :setBeamWeaponTurret(9, 120, -90, 6)
    :setBeamWeaponTurret(10, 120, 90, 6)
    :setBeamWeaponTurret(11, 120, 90, 6)
    :setEnergyStorage(1200)
    :setTubes(2, 8.0)
    :setWeaponStorage("Homing", 6)
    :setWeaponStorage("Mine", 6)
    :setTubeDirection(0, 0)
    :setWeaponTubeExclusiveFor(0, "Homing")
    :setTubeDirection(1, 180)
    :setWeaponTubeExclusiveFor(1, "Mine")
    :setShields(1200, 1200)
    :setSpeed(30, 2, 6)
    :setCombatManeuver(800, 500)
    :setRepairCrewCount(8)
    :addRoomSystem(0, 1, 2, 4, "RearShield")
    :addRoom(3, 0, 2, 1)
    :addRoomSystem(7, 0, 2, 1, "Maneuver")
    :addRoomSystem(11, 0, 2, 1, "MissileSystem")
    :addRoomSystem(2, 1, 4, 2, "Reactor")
    :addRoomSystem(6, 1, 4, 2, "Warp")
    :addRoomSystem(10, 1, 4, 2, "DockingBay")
    :addRoomSystem(14, 2, 2, 2, "FrontShield")
    :addRoomSystem(2, 3, 4, 2, "Impulse")
    :addRoomSystem(6, 3, 4, 2, "JumpDrive")
    :addRoomSystem(10, 3, 4, 2, "Sensors")
    :addRoom(3, 5, 2, 1)
    :addRoom(7, 5, 2, 1)
    :addRoomSystem(11, 5, 2, 1, "Beamweapons")
    :addDoor(3, 1, true)
    :addDoor(7, 1, true)
    :addDoor(11, 1, true)
    :addDoor(2, 2, false)
    :addDoor(6, 1, false)
    :addDoor(10, 2, false)
    :addDoor(14, 3, false)
    :addDoor(10, 4, false)
    :addDoor(6, 3, false)
    :addDoor(8, 3, true)
    :addDoor(4, 5, true)
    :addDoor(8, 5, true)
    :addDoor(12, 5, true)
