--[[                  Destroyers
Destroyers are larger combat-oriented ships. They pack significant firepower
and shielding, and often carry jump drives for intersystem patrol.
They generally have 4 or more shield sections and run with a crew of 50 to 250.
----------------------------------------------------------]]

-- Atlantis X23
local template = ShipTemplate()
    :setName("Atlantis X23")
    :setLocaleName(_("ship", "Atlantis X23"))
    :setClass(_("class", "Destroyer"), _("subclass", "Escort"))
    :setModel("battleship_destroyer_1_upgraded")
    :setDescription(
        _(
            [[The Atlantis X23 is the smallest model of destroyer, and its combination of frigate-like size and corvette-like power makes it an excellent escort ship when defending larger ships against multiple smaller enemies. Because the Atlantis X23 is fitted with a jump drive, it can also serve as an intersystem patrol craft.]]
        )
    )
    :setRadarTrace("dread.png")
    :setHull(100)
    :setShields(200, 200, 200, 200)
    :setSpeed(30, 3.5, 5)
    :setJumpDrive(true)
    :setBeam(0, 100, -20, 1500.0, 6.0, 8)
    :setBeam(1, 100, 20, 1500.0, 6.0, 8)
    :setBeam(2, 100, 180, 1500.0, 6.0, 8)
    :setTubes(4, 10.0)
    :setWeaponStorage("HVLI", 20)
    :setWeaponStorage("Homing", 4)
    :setTubeDirection(0, -90)
    :setTubeDirection(1, -90)
    :setTubeDirection(2, 90)
    :setTubeDirection(3, 90)

-- Atlantis
local variation = template
    :copy("Atlantis")
    :setLocaleName(_("playerShip", "Atlantis"))
    :setType("playership")
variation
    :setDescription(
        _(
            [[A refitted Atlantis X23 for more general tasks. The large shield system has been replaced with an advanced combat maneuvering systems and improved impulse engines. Its missile loadout is also more diverse. Mistaking the modified Atlantis for an Atlantis X23 would be a deadly mistake.]]
        )
    )
    :setShields(200, 200)
    :setHull(250)
    :setSpeed(90, 10, 20)
    :setCombatManeuver(400, 250)
    :setBeam(2, 0, 0, 0, 0, 0)
    :setWeaponStorage("Homing", 12)
    :setWeaponStorage("Nuke", 4)
    :setWeaponStorage("Mine", 8)
    :setWeaponStorage("EMP", 6)
    :setTubes(5, 8.0)
    :weaponTubeDisallowMissle(0, "Mine")
    :weaponTubeDisallowMissle(1, "Mine")
    :weaponTubeDisallowMissle(2, "Mine")
    :weaponTubeDisallowMissle(3, "Mine")
    :setTubeDirection(4, 180)
    :setWeaponTubeExclusiveFor(4, "Mine")
    :addRoomSystem(1, 0, 2, 1, "Maneuver")
    :addRoomSystem(1, 1, 2, 1, "BeamWeapons")
    :addRoomSystem(2, 2, 2, 1, "DockingBay")
    :addRoomSystem(0, 3, 1, 2, "RearShield")
    :addRoomSystem(1, 3, 2, 2, "Reactor")
    :addRoomSystem(3, 3, 2, 2, "Warp")
    :addRoomSystem(5, 3, 1, 2, "JumpDrive")
    :addRoom(6, 3, 2, 1)
    :addRoom(6, 4, 2, 1)
    :addRoomSystem(8, 3, 1, 2, "FrontShield")
    :addRoom(2, 5, 2, 1)
    :addRoomSystem(1, 6, 2, 1, "MissileSystem")
    :addRoomSystem(1, 7, 2, 1, "Impulse")
    :addDoor(1, 1, true)
    :addDoor(2, 2, true)
    :addDoor(3, 3, true)
    :addDoor(1, 3, false)
    :addDoor(3, 4, false)
    :addDoor(3, 5, true)
    :addDoor(2, 6, true)
    :addDoor(1, 7, true)
    :addDoor(5, 3, false)
    :addDoor(6, 3, false)
    :addDoor(6, 4, false)
    :addDoor(8, 3, false)
    :addDoor(8, 4, false)

-- Starhammer II
template = ShipTemplate()
    :setName("Starhammer II")
    :setLocaleName(_("ship", "Starhammer II"))
    :setClass(_("class", "Destroyer"), _("subclass", "Assault"))
    :setModel("battleship_destroyer_4_upgraded")
    :setDescription(
        _(
            [[Contrary to its predecessor, the Starhammer II lives up to its name. By resolving the original Starhammer's power and heat management issues, the updated model makes for a phenomenal frontal assault ship. Its low speed makes it difficult to position, but when in the right place at the right time, even the strongest shields can't withstand a Starhammer's assault for long.]]
        )
    )
    :setRadarTrace("dread.png")
    :setHull(200)
    :setShields(450, 350, 150, 150, 350)
    :setSpeed(35, 6, 10)
    :setJumpDrive(true)
    :setBeam(0, 60, -10, 2000.0, 8.0, 11)
    :setBeam(1, 60, 10, 2000.0, 8.0, 11)
    :setBeam(2, 60, -20, 1500.0, 8.0, 11)
    :setBeam(3, 60, 20, 1500.0, 8.0, 11)
    :setTubes(2, 10.0)
    :setWeaponStorage("HVLI", 20)
    :setWeaponStorage("Homing", 4)
    :setWeaponStorage("EMP", 2)
    :weaponTubeDisallowMissle(1, "EMP")

-- Crucible
template = ShipTemplate()
    :setName("Crucible")
    :setLocaleName(_("playerShip", "Crucible"))
    :setClass(_("class", "Destroyer"), _("subclass", "Missile"))
    :setModel("LaserCorvetteRed")
    :setType("playership")
    :setDescription(
        _(
            [[The Crucible bears a number of missile tubes around its hull. Beams were deemed lower priority, though they are still present. It has stronger defenses than a frigate, but not as strong as the Atlantis.]]
        )
    )
    :setRadarTrace("laser.png")
    :setHull(160)
    :setShields(160, 160)
    :setSpeed(80, 15, 40)
    :setCombatManeuver(400, 250)
    :setJumpDrive(false)
    :setWarpSpeed(750)
    :setBeam(0, 70, -30, 1000.0, 6.0, 5)
    :setBeam(1, 70, 30, 1000.0, 6.0, 5)
    :setTubes(6, 8.0)
    :setWeaponStorage("HVLI", 24)
    :setWeaponStorage("Homing", 8)
    :setWeaponStorage("EMP", 6)
    :setWeaponStorage("Nuke", 4)
    :setWeaponStorage("Mine", 6)
    :setTubeDirection(0, 0)
    :setTubeSize(0, "small")
    :setTubeDirection(1, 0)
    :setTubeDirection(2, 0)
    :setTubeSize(2, "large")
    :setTubeDirection(3, -90)
    :setTubeDirection(4, 90)
    :setTubeDirection(5, 180)
    :setWeaponTubeExclusiveFor(0, "HVLI")
    :setWeaponTubeExclusiveFor(1, "HVLI")
    :setWeaponTubeExclusiveFor(2, "HVLI")
    :weaponTubeDisallowMissle(3, "Mine")
    :weaponTubeDisallowMissle(4, "Mine")
    :setWeaponTubeExclusiveFor(5, "Mine")
    :setRepairCrewCount(4)
    :addRoomSystem(2, 0, 2, 1, "Maneuver")
    :addRoomSystem(1, 1, 2, 1, "BeamWeapons")
    :addRoomSystem(0, 2, 3, 2, "RearShield")
    :addRoomSystem(1, 4, 2, 1, "Reactor")
    :addRoomSystem(2, 5, 2, 1, "Warp")
    :addRoomSystem(3, 1, 3, 2, "JumpDrive")
    :addRoomSystem(3, 3, 3, 2, "FrontShield")
    :addRoomSystem(6, 2, 6, 2, "DockingBay")
    :addRoomSystem(9, 1, 2, 1, "MissileSystem")
    :addRoomSystem(9, 4, 2, 1, "Impulse")
    :addDoor(2, 1, true)
    :addDoor(1, 2, true)
    :addDoor(1, 4, true)
    :addDoor(2, 5, true)
    :addDoor(3, 2, false)
    :addDoor(4, 3, true)
    :addDoor(6, 3, false)
    :addDoor(9, 2, true)
    :addDoor(10, 4, true)

-- Maverick
template = ShipTemplate()
    :setName("Maverick")
    :setLocaleName(_("playerShip", "Maverick"))
    :setClass(_("class", "Destroyer"), _("subclass", "Gunner"))
    :setModel("LaserCorvetteGreen")
    :setType("playership")
    :setDescription(
        _(
            [[A number of beams bristle from various points on this gunner. Weapon tubes were deemed lower priority, though they are still present. It has stronger defenses than a frigate, but not as strong as the Atlantis.]]
        )
    )
    :setRadarTrace("laser.png")
    :setHull(160)
    :setShields(160, 160)
    :setSpeed(80, 15, 40)
    :setCombatManeuver(400, 250)
    :setJumpDrive(false)
    :setWarpSpeed(800)
    :setBeam(0, 10, 0, 2000.0, 6.0, 6)
    :setBeam(1, 90, -20, 1500.0, 6.0, 8)
    :setBeam(2, 90, 20, 1500.0, 6.0, 8)
    :setBeam(3, 40, -70, 1000.0, 4.0, 6)
    :setBeam(4, 40, 70, 1000.0, 4.0, 6)
    :setBeam(5, 10, 180, 800.0, 6.0, 4)
    :setBeamWeaponTurret(5, 180, 180, 0.5)
    :setTubes(3, 8.0)
    :setWeaponStorage("HVLI", 10)
    :setWeaponStorage("Homing", 6)
    :setWeaponStorage("EMP", 4)
    :setWeaponStorage("Nuke", 2)
    :setWeaponStorage("Mine", 2)
    :setTubeDirection(0, -90)
    :setTubeDirection(1, 90)
    :setTubeDirection(2, 180)
    :weaponTubeDisallowMissle(0, "Mine")
    :weaponTubeDisallowMissle(1, "Mine")
    :setWeaponTubeExclusiveFor(2, "Mine")
    :setRepairCrewCount(4)
    :addRoomSystem(2, 0, 2, 1, "Maneuver")
    :addRoomSystem(1, 1, 2, 1, "BeamWeapons")
    :addRoomSystem(0, 2, 3, 2, "RearShield")
    :addRoomSystem(1, 4, 2, 1, "Reactor")
    :addRoomSystem(2, 5, 2, 1, "Warp")
    :addRoomSystem(3, 1, 3, 2, "JumpDrive")
    :addRoomSystem(3, 3, 3, 2, "FrontShield")
    :addRoomSystem(6, 2, 6, 2, "DockingBay")
    :addRoomSystem(9, 1, 2, 1, "MissileSystem")
    :addRoomSystem(9, 4, 2, 1, "Impulse")
    :addDoor(2, 1, true)
    :addDoor(1, 2, true)
    :addDoor(1, 4, true)
    :addDoor(2, 5, true)
    :addDoor(3, 2, false)
    :addDoor(4, 3, true)
    :addDoor(6, 3, false)
    :addDoor(9, 2, true)
    :addDoor(10, 4, true)
