--[[                  Light Carriers
Light carriers are small to medium vessels designed to carry, deploy,
and support starfighters and other small craft. They are typically
equipped with docking facilities and supplies to sustain small strike
groups on extended deployments.
----------------------------------------------------------]]

-- Saipan
local template = ShipTemplate()
    :setName("Saipan")
    :setLocaleName(_("playerShip", "Saipan"))
    :setModel("battleship_destroyer_5_upgraded")
    :setType("playership")
    :setClass(_("class", "Light Carrier"), _("subclass", "Escort"))
    :setDescription(
        _(
            [[The Saipan mixes most of the strengths of the corvette class with carrier capability. Its weapons compare favorably with other corvette class ships. Having fighters use the Saipan as a base can really ruin an enemy's day.]]
        )
    )
    :setRadarTrace("cruiser.png")
    :setHull(180)
    :setShields(90, 90)
    :setSpeed(80, 10, 20)
    :setJumpDrive(true)
    :setCombatManeuver(400, 250)
    :setExternalDockClasses(_("class", "Frigate"))
    :setInternalDockClasses(_("class", "Starfighter"), _("class", "Cargo"))
    :setSharesEnergyWithDocked(false)
    :setRepairDocked(true)
    :setRestocksScanProbes(false)
    :setRestocksMissilesDocked(true)
    :setBeam(0, 120, -40, 1000.0, 6.0, 6)
    :setBeam(1, 120, 40, 1000.0, 6.0, 6)
    :setBeam(2, 10, 180, 800.0, 6.0, 4)
    :setBeamWeaponTurret(2, 60, 180, 0.5)
    :setTubes(5, 8.0)
    :setTubeDirection(0, 0)
    :setTubeSize(0, "small")
    :setTubeLoadTime(0, 6)
    :setWeaponTubeExclusiveFor(0, "HVLI")
    :setTubeDirection(1, 0)
    :setTubeSize(1, "medium")
    :setTubeLoadTime(1, 8)
    :weaponTubeDisallowMissle(1, "Mine")
    :setTubeDirection(2, -90)
    :setTubeSize(2, "large")
    :setTubeLoadTime(2, 12)
    :setWeaponTubeExclusiveFor(2, "HVLI")
    :weaponTubeAllowMissle(2, "Homing")
    :setTubeDirection(3, 90)
    :setTubeSize(3, "large")
    :setTubeLoadTime(3, 12)
    :setWeaponTubeExclusiveFor(3, "HVLI")
    :weaponTubeAllowMissle(3, "Homing")
    :setTubeDirection(4, 180)
    :setTubeSize(4, "medium")
    :setTubeLoadTime(4, 10)
    :setWeaponTubeExclusiveFor(4, "Mine")
    :setWeaponStorage("Homing", 8)
    :setWeaponStorage("Nuke", 4)
    :setWeaponStorage("Mine", 6)
    :setWeaponStorage("EMP", 6)
    :setWeaponStorage("HVLI", 16)
    :setRepairCrewCount(5)
    :addRoomSystem(0, 0, 4, 1, "Maneuver")
    :addRoomSystem(1, 1, 2, 2, "Impulse")
    :addRoomSystem(3, 2, 3, 1, "Warp")
    :addRoomSystem(6, 2, 2, 1, "BeamWeapons")
    :addRoomSystem(2, 3, 2, 2, "JumpDrive")
    :addRoomSystem(7, 3, 3, 2, "FrontShield")
    :addRoomSystem(1, 5, 2, 2, "Reactor")
    :addRoomSystem(3, 5, 3, 1, "MissileSystem")
    :addRoomSystem(6, 5, 2, 1, "DockingBay")
    :addRoomSystem(0, 7, 4, 1, "RearShield")
    :addDoor(1, 1, true)
    :addDoor(2, 3, true)
    :addDoor(3, 3, true)
    :addDoor(6, 2, false)
    :addDoor(7, 3, true)
    :addDoor(2, 5, true)
    :addDoor(3, 5, true)
    :addDoor(6, 5, false)
    :addDoor(7, 5, true)
    :addDoor(1, 7, true)
